# Generated by Django 4.2.2 on 2023-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.CharField(choices=[('maths', 'Mathématiques'), ('francais', 'Français'), ('histoire', 'Histoire')], default='maths', max_length=50)),
                ('professeur', models.CharField(choices=[('prof1', 'Professeur 1'), ('prof2', 'Professeur 2'), ('prof3', 'Professeur 3')], default='prof1', max_length=50)),
                ('quota_total', models.IntegerField(default=30)),
                ('heure', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
            ],
        ),
    ]
