# Generated by Django 4.2.2 on 2023-06-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiList',
            fields=[
                ('license', models.CharField(choices=[('licence1', 'Licence 1'), ('licence2', 'Licence 2'), ('licence3', 'Licence 3')], default='licence1', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.CharField(choices=[('maths', 'Mathématiques'), ('francais', 'Français'), ('histoire', 'Histoire')], default='maths', max_length=50)),
                ('professeur', models.CharField(choices=[('prof1', 'Professeur 1'), ('prof2', 'Professeur 2'), ('prof3', 'Professeur 3')], default='prof1', max_length=50)),
                ('filiere', models.CharField(choices=[('filiere1', 'Filière 1'), ('filiere2', 'Filière 2'), ('filiere3', 'Filière 3')], default='filiere1', max_length=50)),
                ('quota_total', models.IntegerField(default=30)),
                ('list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscription.emploilist')),
            ],
        ),
    ]
