# Generated by Django 4.2.2 on 2023-06-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi',
            name='list',
        ),
    ]
