# Generated by Django 4.2.2 on 2023-06-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_emploi_salle_alter_emploi_heure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi',
            name='heure',
        ),
        migrations.AddField(
            model_name='emploi',
            name='quota_restante',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='NouveauEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('heure_debut', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('heure_fin', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('duree_cours', models.IntegerField()),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.emploi')),
            ],
        ),
    ]
