# Generated by Django 4.2.2 on 2023-06-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_remove_nouveauemploi_date_nouveauemploi_jour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nouveauemploi',
            name='heure_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nouveauemploi',
            name='heure_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nouveauemploi',
            name='jour',
            field=models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10),
        ),
    ]
