# Generated by Django 4.2.2 on 2023-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_nouveauemploi_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nouveauemploi',
            name='heure_debut',
            field=models.TimeField(verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='nouveauemploi',
            name='heure_fin',
            field=models.TimeField(verbose_name='Heure de fin'),
        ),
    ]
