# Generated by Django 4.2.2 on 2023-06-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_alter_nouveauemploi_heure_debut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nouveauemploi',
            options={'verbose_name': 'Nouvel emploi', 'verbose_name_plural': 'Nouveaux emplois'},
        ),
    ]
