# Generated by Django 4.2.2 on 2023-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0011_alter_emploi_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi',
            name='salle',
        ),
        migrations.AddField(
            model_name='nouveauemploi',
            name='salle',
            field=models.CharField(choices=[('IRAN1', 'IRAN1'), ('IRAN2', 'IRAN2'), ('FAKAMBI', 'FAKAMBI')], default='IRAN1', max_length=50),
        ),
    ]
