# Generated by Django 4.2.2 on 2023-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_remove_emploi_salle_nouveauemploi_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='professeur',
            field=models.CharField(choices=[('Professeur 1', 'nom 1'), ('Professeur 2', 'nom 2'), ('Professeur 3', 'nom 3')], default='prof1', max_length=50),
        ),
    ]
