# Generated by Django 4.2.2 on 2023-06-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0015_nouveauemploi_groupe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NouveauEmploi',
            new_name='NouveauEmploi_L1',
        ),
        migrations.CreateModel(
            name='NouveauEmploi_M2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('duree_cours', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=False)),
                ('salle', models.CharField(choices=[('IRAN1', 'IRAN1'), ('IRAN2', 'IRAN2'), ('FAKAMBI', 'FAKAMBI')], default='IRAN1', max_length=50)),
                ('groupe', models.CharField(choices=[('SI', 'SI'), ('IA', 'IA'), ('SEOIT', 'SEOIT'), ('GL', 'GL'), ('IM', 'IM'), ('Groupe 1', 'Groupe 1'), ('Groupe 2', 'Groupe 2')], default='Groupe 1', max_length=50)),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.emploi')),
            ],
            options={
                'verbose_name': 'Nouvel emploi',
                'verbose_name_plural': 'Nouveaux emplois',
            },
        ),
        migrations.CreateModel(
            name='NouveauEmploi_M1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('duree_cours', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=False)),
                ('salle', models.CharField(choices=[('IRAN1', 'IRAN1'), ('IRAN2', 'IRAN2'), ('FAKAMBI', 'FAKAMBI')], default='IRAN1', max_length=50)),
                ('groupe', models.CharField(choices=[('SI', 'SI'), ('IA', 'IA'), ('SEOIT', 'SEOIT'), ('GL', 'GL'), ('IM', 'IM'), ('Groupe 1', 'Groupe 1'), ('Groupe 2', 'Groupe 2')], default='Groupe 1', max_length=50)),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.emploi')),
            ],
            options={
                'verbose_name': 'Nouvel emploi',
                'verbose_name_plural': 'Nouveaux emplois',
            },
        ),
        migrations.CreateModel(
            name='NouveauEmploi_L3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('duree_cours', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=False)),
                ('salle', models.CharField(choices=[('IRAN1', 'IRAN1'), ('IRAN2', 'IRAN2'), ('FAKAMBI', 'FAKAMBI')], default='IRAN1', max_length=50)),
                ('groupe', models.CharField(choices=[('SI', 'SI'), ('IA', 'IA'), ('SEOIT', 'SEOIT'), ('GL', 'GL'), ('IM', 'IM'), ('Groupe 1', 'Groupe 1'), ('Groupe 2', 'Groupe 2')], default='Groupe 1', max_length=50)),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.emploi')),
            ],
            options={
                'verbose_name': 'Nouvel emploi',
                'verbose_name_plural': 'Nouveaux emplois',
            },
        ),
        migrations.CreateModel(
            name='NouveauEmploi_L2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('duree_cours', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=False)),
                ('salle', models.CharField(choices=[('IRAN1', 'IRAN1'), ('IRAN2', 'IRAN2'), ('FAKAMBI', 'FAKAMBI')], default='IRAN1', max_length=50)),
                ('groupe', models.CharField(choices=[('SI', 'SI'), ('IA', 'IA'), ('SEOIT', 'SEOIT'), ('GL', 'GL'), ('IM', 'IM'), ('Groupe 1', 'Groupe 1'), ('Groupe 2', 'Groupe 2')], default='Groupe 1', max_length=50)),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.emploi')),
            ],
            options={
                'verbose_name': 'Nouvel emploi',
                'verbose_name_plural': 'Nouveaux emplois',
            },
        ),
    ]
