# Generated by Django 4.2.2 on 2023-06-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0016_rename_nouveauemploi_nouveauemploi_l1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nouveauemploi_l1',
            options={'verbose_name': 'Nouvel emploi Licence 1', 'verbose_name_plural': 'Nouveaux emplois Licence 1'},
        ),
        migrations.AlterModelOptions(
            name='nouveauemploi_l2',
            options={'verbose_name': 'Nouvel emploi Licence 2', 'verbose_name_plural': 'Nouveaux emplois Licence 2'},
        ),
        migrations.AlterModelOptions(
            name='nouveauemploi_l3',
            options={'verbose_name': 'Nouvel emploi Licence 3', 'verbose_name_plural': 'Nouveaux emplois Licence 3'},
        ),
        migrations.AlterModelOptions(
            name='nouveauemploi_m1',
            options={'verbose_name': 'Nouvel emploi Master 1', 'verbose_name_plural': 'Nouveaux emplois Master 1'},
        ),
        migrations.AlterModelOptions(
            name='nouveauemploi_m2',
            options={'verbose_name': 'Nouvel emploi Master 2', 'verbose_name_plural': 'Nouveaux emplois Master 2'},
        ),
        migrations.RemoveField(
            model_name='emploi',
            name='Licence',
        ),
    ]
