# Generated by Django 4.2.2 on 2023-06-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0017_alter_nouveauemploi_l1_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(max_length=100)),
                ('contenu', models.JSONField()),
            ],
        ),
    ]
