# Generated by Django 4.2.2 on 2023-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0019_delete_historiquedashboard_nouveauemploi_l1_texte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nouveauemploi_l1',
            name='semaine',
            field=models.CharField(default='Semaine du __ au __', max_length=50),
        ),
        migrations.AddField(
            model_name='nouveauemploi_l2',
            name='semaine',
            field=models.CharField(default='Semaine du __ au __', max_length=50),
        ),
        migrations.AddField(
            model_name='nouveauemploi_l3',
            name='semaine',
            field=models.CharField(default='Semaine du __ au __', max_length=50),
        ),
        migrations.AddField(
            model_name='nouveauemploi_m1',
            name='semaine',
            field=models.CharField(default='Semaine du __ au __', max_length=50),
        ),
        migrations.AddField(
            model_name='nouveauemploi_m2',
            name='semaine',
            field=models.CharField(default='Semaine du __ au __', max_length=50),
        ),
    ]
