# Generated by Django 4.2.2 on 2023-06-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0020_nouveauemploi_l1_semaine_nouveauemploi_l2_semaine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='cours',
            field=models.CharField(default='maths', max_length=50),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='professeur',
            field=models.CharField(default='prof1', max_length=50),
        ),
    ]
