# Generated by Django 4.2.2 on 2023-06-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0022_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
