# Generated by Django 4.2.2 on 2023-07-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0023_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField(default='Description', max_length=100)),
                ('emploi_du_temps_L1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_l1')),
                ('emploi_du_temps_L2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_l2')),
                ('emploi_du_temps_L3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_l3')),
                ('emploi_du_temps_M1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_m1')),
                ('emploi_du_temps_M2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_m2')),
            ],
        ),
    ]
