# Generated by Django 4.2.2 on 2023-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0024_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='quota_restante',
            field=models.IntegerField(default=models.IntegerField(default=30)),
        ),
    ]
