# Generated by Django 4.2.2 on 2023-07-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0025_alter_emploi_quota_restante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='contenu',
        ),
        migrations.AddField(
            model_name='historique',
            name='Description',
            field=models.TextField(default='Avez vous un tag a ajouter ? (facultatif)', max_length=100),
        ),
        migrations.AlterField(
            model_name='historique',
            name='emploi_du_temps_L1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_l1'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='emploi_du_temps_L2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_l2'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='emploi_du_temps_L3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_l3'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='emploi_du_temps_M1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_m1'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='emploi_du_temps_M2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inscription.nouveauemploi_m2'),
        ),
    ]
