# Generated by Django 4.2.2 on 2023-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0026_remove_historique_contenu_historique_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='Description',
            field=models.TextField(default='Historique du ', max_length=100),
        ),
    ]
