# Generated by Django 4.2.2 on 2023-07-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0028_alter_nouveauemploi_l1_salle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_notification', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
