# Generated by Django 5.0.3 on 2024-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0029_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='texte_notification',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
